-- Offline tests for the identity a run records: the DCS build, the theatre's
-- directory under the install, and the fingerprint of its data files.
--
-- Run from the repository root with a plain lua5.1.
--
-- Everything here is read off a fake install laid out the way the real one
-- is, including the two things the real one does that the documents did not
-- foresee: a theatre whose data files are named after neither its id nor its
-- directory in any one rule, and a directory under Mods/terrains that is not
-- a theatre at all.

package.path = "extractor/?.lua;extractor/test/support/?.lua;" .. package.path

local T = require("testing")
local E = require("DcsTerrainExtract")
local FakeFs = require("fakefs")

local INSTALL = "C:/DCS"
local TERRAINS = INSTALL .. "/Mods/terrains"

-- A container header as the real files carry it: two u32 fields, then the
-- payload size as a little-endian u64 at bytes 8 to 15.
local function header(payload)
  local bytes = { 2, 0, 0, 0, 48, 0, 0, 0 }
  for _ = 1, 8 do
    bytes[#bytes + 1] = payload % 256
    payload = math.floor(payload / 256)
  end
  return string.char(unpack(bytes))
end

-- The shape of ED's entry.lua around the one line that matters. update_id
-- comes first on purpose: a pattern that matched the first `id` it saw would
-- take it.
local function entry(id)
  return "if not USE_TERRAIN4 then\n\treturn\nend\n\ntheatre =\n{\n"
    .. "\t['developerName'] = \"x\";\n"
    .. "\t['update_id'] = \"" .. id:upper() .. "_terrain\";\n"
    .. "\t['id'] = \"" .. id .. "\";\n"
    .. "\t['localizedName'] = \"x\";\n"
    .. "} -- end of theatre\n"
end

local BUILD = '{\n "WARNING": "DO NOT EDIT this file. You may break your install!",\n'
  .. ' "version": "2.9.29.27468",\n "timestamp": "20260902-093323",\n'
  .. ' "arch": "x86_64",\n "modules": [\n  "WORLD",\n  "SINAIMAP_terrain"\n ],\n'
  .. ' "launch": "bin/DCS.exe"\n}\n'

local function new_install()
  local fs = FakeFs.new()
  fs.cwd = "C:\\DCS"
  fs.files[INSTALL .. "/autoupdate.cfg"] = BUILD

  -- Sinai: id SinaiMap, a lowercase surface directory, and the siblings that
  -- sit beside each file on the real install.
  local sinai = TERRAINS .. "/Sinai"
  fs.files[sinai .. "/entry.lua"] = entry("SinaiMap")
  fs.files[sinai .. "/surface/SinaiMap.surface5"] = header(43964216) .. string.rep("s", 300)
  fs.files[sinai .. "/surface/SinaiMap.ng5"] = "n"
  fs.files[sinai .. "/surface/SinaiMap.onlay.sup4"] = "o"
  fs.files[sinai .. "/surface/SinaiMap.tile"] = "t"
  fs.files[sinai .. "/roads/SinaiMap.rn4"] = header(200) .. string.rep("r", 184)
  fs.files[sinai .. "/roads/SinaiMap.routes"] = "x"
  fs.files[sinai .. "/Scenes/SinaiMap.scn5"] = header(11888248) .. string.rep("c", 100)
  fs.mtimes[sinai .. "/surface/SinaiMap.surface5"] = 1756800001
  fs.mtimes[sinai .. "/roads/SinaiMap.rn4"] = 1756800003
  fs.mtimes[sinai .. "/Scenes/SinaiMap.scn5"] = 1756800002

  -- Cold War Germany: id GermanyCW, files named after the directory.
  local germany = TERRAINS .. "/GermanyColdWar"
  fs.files[germany .. "/entry.lua"] = entry("GermanyCW")
  fs.files[germany .. "/surface/GermanyColdWar.surface5"] = header(1) .. "g"

  -- Caucasus: id and directory agree, and Surface is capitalized.
  local caucasus = TERRAINS .. "/Caucasus"
  fs.files[caucasus .. "/entry.lua"] = entry("Caucasus")
  fs.files[caucasus .. "/Surface/Caucasus.surface5"] = header(43964216)

  -- Kola: under Mods/terrains, not a theatre.
  fs.files[TERRAINS .. "/Kola/radio.lua"] = "return {}"
  return fs
end

--------------------------------------------------------------------------------
T.group("the build comes out of autoupdate.cfg")
--------------------------------------------------------------------------------

local build = E.parse_build(BUILD)
T.eq("version", build.dcs_build, "2.9.29.27468")
T.eq("timestamp", build.dcs_build_timestamp, "20260902-093323")

local function refused(value, err)
  T.eq("refused", value, nil)
  return err
end

T.eq("no version is refused",
  refused(E.parse_build('{"timestamp": "20260902-093323"}')):find("has no version", 1, true) ~= nil, true)
T.eq("an empty timestamp is refused",
  refused(E.parse_build('{"version": "2.9", "timestamp": ""}')):find("has no timestamp", 1, true) ~= nil, true)
T.eq("not JSON is refused",
  refused(E.parse_build("version = 2.9")):find("is not JSON", 1, true) ~= nil, true)
T.eq("a bare value is refused",
  refused(E.parse_build("42")):find("is not an object: 42", 1, true) ~= nil, true)
T.eq("an array has no version",
  refused(E.parse_build("[1, 2]")):find("has no version", 1, true) ~= nil, true)

local fs = new_install()
E.fs = fs
T.eq("read off the install", E.read_build(INSTALL).dcs_build, "2.9.29.27468")
fs.files[INSTALL .. "/autoupdate.cfg"] = nil
T.eq("a missing file says so",
  refused(E.read_build(INSTALL)):find("cannot be read", 1, true) ~= nil, true)

--------------------------------------------------------------------------------
T.group("the install directory is where DCS runs from")
--------------------------------------------------------------------------------

T.eq("forward slashes", E.install_dir(), "C:/DCS")
fs.cwd = nil
local nodir, why = E.install_dir()
T.eq("none without lfs", nodir, nil)
T.eq("and it says so", why:find("install directory is unknown", 1, true) ~= nil, true)

--------------------------------------------------------------------------------
T.group("the id is the one entry.lua declares")
--------------------------------------------------------------------------------

T.eq("ED's own form", E.entry_id(entry("SinaiMap")), "SinaiMap")
T.eq("update_id is not the id", E.entry_id("['update_id'] = \"SINAIMAP_terrain\";"), nil)
T.eq("double-quoted key", E.entry_id('["id"] = "Syria",'), "Syria")
T.eq("single-quoted value", E.entry_id("['id'] = 'Kola';"), "Kola")
T.eq("spaces inside the brackets", E.entry_id("[ 'id' ]  =  \"Nevada\""), "Nevada")
T.eq("a bare assignment as a last resort", E.entry_id("theatre = {\n  id = \"Falklands\",\n}"), "Falklands")
T.eq("a bracketed key wins over a bare one",
  E.entry_id("skins = { id = \"Theme\" }\n['id'] = \"Afghanistan\";"), "Afghanistan")
T.eq("an empty id is none", E.entry_id("['id'] = \"\";"), nil)
T.eq("no id is none", E.entry_id("theatre = {}"), nil)
T.eq("not a string is none", E.entry_id(nil), nil)

--------------------------------------------------------------------------------
T.group("the theatre directory is found by its id")
--------------------------------------------------------------------------------

fs = new_install()
E.fs = fs

T.eq("an id that is not the directory name", E.find_terrain_dir(INSTALL, "SinaiMap"), "Sinai")
T.eq("another", E.find_terrain_dir(INSTALL, "GermanyCW"), "GermanyColdWar")
T.eq("an id that is", E.find_terrain_dir(INSTALL, "Caucasus"), "Caucasus")

local missing, mwhy = E.find_terrain_dir(INSTALL, "Nowhere")
T.eq("an unknown id is refused", missing, nil)
T.eq("naming the id", mwhy:find("no theatre under Mods/terrains has id Nowhere", 1, true) ~= nil, true)
T.eq("and what was scanned", mwhy:find("Sinai=SinaiMap", 1, true) ~= nil, true)
T.eq("a directory with no entry file is passed over", mwhy:find("Kola", 1, true), nil)

-- ADR 0011: before failing, the id as a directory name.
fs.mkdir(TERRAINS .. "/Nevada")
T.eq("a directory named for the id is the fallback", E.find_terrain_dir(INSTALL, "Nevada"), "Nevada")

T.eq("no id is refused", refused(E.find_terrain_dir(INSTALL, nil)):find("no theatre id", 1, true) ~= nil, true)
E.fs = FakeFs.new()
T.eq("no Mods/terrains is refused",
  refused(E.find_terrain_dir(INSTALL, "Caucasus")):find("Mods/terrains cannot be listed", 1, true) ~= nil, true)

--------------------------------------------------------------------------------
T.group("each data file is the one with its extension")
--------------------------------------------------------------------------------

fs = new_install()
E.fs = fs

T.eq("found among its siblings, spelled as the disk spells it",
  E.find_terrain_file(INSTALL, "Sinai", "Surface", ".surface5"),
  "Mods/terrains/Sinai/surface/SinaiMap.surface5")
T.eq("the capitalized directory where that is the spelling",
  E.find_terrain_file(INSTALL, "Caucasus", "Surface", ".surface5"),
  "Mods/terrains/Caucasus/Surface/Caucasus.surface5")
T.eq("the routes file beside it is not a roads file",
  E.find_terrain_file(INSTALL, "Sinai", "roads", ".rn4"),
  "Mods/terrains/Sinai/roads/SinaiMap.rn4")
T.eq("named after the directory rather than the id",
  E.find_terrain_file(INSTALL, "GermanyColdWar", "Surface", ".surface5"),
  "Mods/terrains/GermanyColdWar/surface/GermanyColdWar.surface5")

fs.files[TERRAINS .. "/Sinai/roads/Other.rn4"] = "x"
T.eq("two candidates are a refusal, not a guess",
  refused(E.find_terrain_file(INSTALL, "Sinai", "roads", ".rn4")):find("2 .rn4 files under Mods/terrains/Sinai/roads: Other.rn4, SinaiMap.rn4", 1, true) ~= nil, true)
fs.files[TERRAINS .. "/Sinai/roads/Other.rn4"] = nil

T.eq("no such directory",
  refused(E.find_terrain_file(INSTALL, "GermanyColdWar", "roads", ".rn4")):find("no roads directory under Mods/terrains/GermanyColdWar", 1, true) ~= nil, true)
fs.files[TERRAINS .. "/GermanyColdWar/roads/GermanyColdWar.routes"] = "x"
T.eq("no such file",
  refused(E.find_terrain_file(INSTALL, "GermanyColdWar", "roads", ".rn4")):find("no .rn4 file under Mods/terrains/GermanyColdWar/roads: has GermanyColdWar.routes", 1, true) ~= nil, true)
T.eq("no such theatre",
  refused(E.find_terrain_file(INSTALL, "Nowhere", "roads", ".rn4")):find("Mods/terrains/Nowhere cannot be listed", 1, true) ~= nil, true)

--------------------------------------------------------------------------------
T.group("a little-endian u64 by arithmetic")
--------------------------------------------------------------------------------

-- The first sixteen bytes of the real Caucasus.surface5, whose payload field
-- reads 43 964 216.
local caucasus_head = string.char(0x02, 0x00, 0x00, 0x00, 0x30, 0x00, 0x00, 0x00,
  0x38, 0xd7, 0x9e, 0x02, 0x00, 0x00, 0x00, 0x00)
T.eq("the payload field", E.u64le(caucasus_head, 9), 43964216)
T.eq("the two u32 fields read as one u64", E.u64le(caucasus_head, 1), 206158430210)
T.eq("the position defaults to the start", E.u64le(caucasus_head), 206158430210)
T.eq("too short is nil", E.u64le(caucasus_head, 10), nil)
T.eq("not a string is nil", E.u64le(nil), nil)
T.eq("a header from the helper reads back", E.u64le(header(6293651208), 9), 6293651208)
T.eq("the largest exact value", E.u64le(header(9007199254740991), 9), 9007199254740991)
T.eq("past exactness is nil", E.u64le(header(9007199254740992), 9), nil)

--------------------------------------------------------------------------------
T.group("eight hex digits by arithmetic")
--------------------------------------------------------------------------------

T.eq("zero", E.hex32(0), "00000000")
T.eq("a time", E.hex32(1700000002), "6553f102")
T.eq("past the signed range", E.hex32(2147483648), "80000000")
T.eq("the largest", E.hex32(4294967295), "ffffffff")
T.raises("too large", function() E.hex32(4294967296) end, "not a whole number below 2^32")
T.raises("negative", function() E.hex32(-1) end, "not a whole number below 2^32")
T.raises("fractional", function() E.hex32(1.5) end, "not a whole number below 2^32")

--------------------------------------------------------------------------------
T.group("a file's fingerprint is its size, its payload field and its time")
--------------------------------------------------------------------------------

fs = new_install()
E.fs = fs

local surface = E.fingerprint_file(INSTALL, "Mods/terrains/Sinai/surface/SinaiMap.surface5")
T.eq("path as given", surface.path, "Mods/terrains/Sinai/surface/SinaiMap.surface5")
T.eq("size from the file system", surface.size, 316)
T.eq("payload from the header", surface.payload_size, 43964216)
T.eq("time from the file system", surface.modified, 1756800001)
T.eq("four keys and no more", E.json(surface),
  '{"modified":1756800001,"path":"Mods/terrains/Sinai/surface/SinaiMap.surface5","payload_size":43964216,"size":316}')

fs.files[TERRAINS .. "/Sinai/surface/short.surface5"] = "ten bytes."
T.eq("a file too short for a header is refused",
  refused(E.fingerprint_file(INSTALL, "Mods/terrains/Sinai/surface/short.surface5")):find("has no container header: 10 bytes read", 1, true) ~= nil, true)
T.eq("an absent file is refused",
  refused(E.fingerprint_file(INSTALL, "Mods/terrains/Sinai/surface/gone.surface5")):find("has no size", 1, true) ~= nil, true)

--------------------------------------------------------------------------------
T.group("the theatre's fingerprint and its digest")
--------------------------------------------------------------------------------

fs = new_install()
E.fs = fs

local fingerprint = E.terrain_fingerprint(INSTALL, "Sinai")
T.eq("surface5", fingerprint.surface5.path, "Mods/terrains/Sinai/surface/SinaiMap.surface5")
T.eq("rn4", fingerprint.rn4.path, "Mods/terrains/Sinai/roads/SinaiMap.rn4")
T.eq("rn4 payload", fingerprint.rn4.payload_size, 200)
T.eq("scn5", fingerprint.scn5.path, "Mods/terrains/Sinai/Scenes/SinaiMap.scn5")
T.eq("scn5 size", fingerprint.scn5.size, 116)

-- The newest of the three times, which is the roads file here, in hex.
T.eq("the digest is the newest time", fingerprint.digest, E.hex32(1756800003))
T.eq("as eight hex digits", fingerprint.digest, "68b6a403")
T.eq("the digest alone",
  E.fingerprint_digest({ surface5 = { modified = 5 }, rn4 = { modified = 9 }, scn5 = { modified = 7 } }),
  "00000009")
T.raises("a file without a time cannot be digested",
  function() E.fingerprint_digest({ surface5 = { modified = 5 }, rn4 = {}, scn5 = { modified = 7 } }) end,
  "rn4 has no modification time")

-- Encoded, so a resume compares the same string run to run.
T.eq("four keys, sorted", E.json(fingerprint):sub(1, 20), '{"digest":"68b6a403"')

-- The synthetic theatre's constants, which the Rust side holds a twin of,
-- follow the same rule: the digest there is the one this function gives.
local S = require("synth_constants")
T.eq("the synth digest follows the rule",
  E.fingerprint_digest({
    surface5 = { modified = S.FINGERPRINT_SURFACE5_MODIFIED },
    rn4 = { modified = S.FINGERPRINT_RN4_MODIFIED },
    scn5 = { modified = S.FINGERPRINT_SCN5_MODIFIED },
  }),
  S.FINGERPRINT_DIGEST)

fs.files[TERRAINS .. "/Sinai/Scenes/SinaiMap.scn5"] = nil
fs.files[TERRAINS .. "/Sinai/Scenes/readme.txt"] = "x"
T.eq("a missing file refuses the whole fingerprint",
  refused(E.terrain_fingerprint(INSTALL, "Sinai")):find("no .scn5 file under Mods/terrains/Sinai/Scenes", 1, true) ~= nil, true)

--------------------------------------------------------------------------------
T.group("the identity job fills the run and says what it found")
--------------------------------------------------------------------------------

T.eq("it is the first prepare job", E.jobs.prepare[1], E.identity_job)

local logged = {}
E.log = function(message) logged[#logged + 1] = message end
E.now_iso = function() return "2026-09-04T09:12:44Z" end
E.clock = function() return 0 end
-- The editor is open on Sinai, whose id is not its directory name.
E.terrain_id = function() return "SinaiMap" end

local function has(line)
  for i = 1, #logged do
    if logged[i] == line then
      return true
    end
  end
  return false
end

local function run_with(install)
  E.fs = install
  local run = E.new_run({
    config = { output_dir = "C:/extract", frame_budget_ms = 5 },
    jobs = { prepare = { E.identity_job }, hook = {}, mission = {} },
  })
  E.start(run)
  -- Idle polls for terrain on its first frame and enters prepare; the next
  -- frame is prepare's.
  E.run_frame(run)
  T.eq("prepare entered", run.state, E.STATE_PREPARE)
  return run, E.run_frame(run)
end

fs = new_install()
local run, after = run_with(fs)
T.eq("prepare is one frame", after, E.STATE_HOOK)
T.eq("theatre from idle", run.identity.theatre, "SinaiMap")
T.eq("build", run.identity.dcs_build, "2.9.29.27468")
T.eq("timestamp", run.identity.dcs_build_timestamp, "20260902-093323")
T.eq("directory", run.identity.terrain_dir, "Sinai")
T.eq("digest", run.identity.terrain_fingerprint.digest, "68b6a403")
T.eq("a file entry", run.identity.terrain_fingerprint.surface5.path,
  "Mods/terrains/Sinai/surface/SinaiMap.surface5")
T.eq("the job is timed", run.timing_ms.identity ~= nil, true)
T.eq("nothing was written", fs.files["C:/extract/manifest.json"], nil)

-- One line per fact, each checkable against the install by hand.
T.eq("install logged", has("install C:/DCS"), true)
T.eq("build logged", has("dcs_build 2.9.29.27468 20260902-093323"), true)
T.eq("directory logged", has("terrain_dir Sinai"), true)
T.eq("each file logged",
  has("surface5 Mods/terrains/Sinai/surface/SinaiMap.surface5 size 316 payload 43964216 modified 1756800001"), true)
T.eq("roads too", has("rn4 Mods/terrains/Sinai/roads/SinaiMap.rn4 size 200 payload 200 modified 1756800003"), true)
T.eq("digest logged", has("terrain_fingerprint 68b6a403"), true)

--------------------------------------------------------------------------------
T.group("the identity job refuses what it cannot read")
--------------------------------------------------------------------------------

local function refuses(install, finding)
  logged = {}
  local r, state = run_with(install)
  T.eq("the run stops", state, E.STATE_STOPPED)
  T.eq("the finding is on the run", r.refusal:sub(1, #finding), finding)
  T.eq("and in the log", has(r.refusal), true)
  T.eq("the identity is not half described", r.identity.dcs_build, nil)
  return r
end

-- The theatre DCS has open is not installed under Mods/terrains.
E.terrain_id = function() return "Nowhere" end
local stopped = refuses(new_install(), "no theatre under Mods/terrains has id Nowhere")
T.eq("the window gets the finding",
  E.problem_for_screen(stopped.refusal), "no theatre under Mods/terrains has id Nowhere.")
E.terrain_id = function() return "SinaiMap" end

fs = new_install()
fs.files[INSTALL .. "/autoupdate.cfg"] = nil
refuses(fs, "autoupdate.cfg cannot be read")

fs = new_install()
fs.cwd = nil
refuses(fs, "the install directory is unknown")

fs = new_install()
fs.files[TERRAINS .. "/Sinai/roads/Other.rn4"] = "x"
refuses(fs, "2 .rn4 files under Mods/terrains/Sinai/roads")

-- Prepare entered with no theatre on the run, which no frame does but a
-- caller of enter could: a refusal, not a raise into DCS.
fs = new_install()
E.fs = fs
local bare = E.new_run({
  config = { output_dir = "C:/extract", frame_budget_ms = 5 },
  jobs = { prepare = { E.identity_job }, hook = {}, mission = {} },
})
E.enter(bare, E.STATE_PREPARE)
T.eq("no theatre is a refusal", E.run_frame(bare), E.STATE_STOPPED)
T.eq("saying so", bare.refusal:sub(1, 26), "no theatre id to look for:")

-- The next Start is a new attempt against whatever the install holds now.
fs = new_install()
fs.files[INSTALL .. "/autoupdate.cfg"] = nil
local again = refuses(fs, "autoupdate.cfg cannot be read")
fs.files[INSTALL .. "/autoupdate.cfg"] = BUILD
T.eq("Start again", E.start(again), true)
E.run_frame(again)
T.eq("and this time it goes through", E.run_frame(again), E.STATE_HOOK)
T.eq("with the identity filled", again.identity.terrain_dir, "Sinai")

T.done()
