-- Offline tests for the JSON decoder.
--
-- Run from the repository root with a plain lua5.1.
--
-- Decoded tables are asserted through E.json of them, because the framework
-- compares with == and two tables are never equal. That makes most of what is
-- here a statement about the round trip, which is what the hook depends on: it
-- writes a manifest, reads it back on resume, and writes it again.

package.path = "extractor/?.lua;extractor/test/support/?.lua;" .. package.path

local T = require("testing")
local E = require("DcsTerrainExtract")

local function round(text)
  return E.json(E.decode(text))
end

--------------------------------------------------------------------------------
T.group("scalars")
--------------------------------------------------------------------------------

T.eq("true", round("true"), "true")
T.eq("false", round("false"), "false")
T.eq("null", round("null"), "null")
T.eq("null is the sentinel", E.decode("null") == E.JSON_NULL, true)

T.eq("zero", E.decode("0"), 0)
T.eq("negative", E.decode("-5"), -5)
T.eq("fraction", E.decode("1.5"), 1.5)
T.eq("exponent", E.decode("1e3"), 1000)
T.eq("signed exponent", E.decode("15e-1"), 1.5)
T.eq("plus exponent", E.decode("15e+1"), 150)
T.eq("capital exponent", E.decode("1E2"), 100)
T.eq("a zero on its own is not a leading zero", E.decode("0.5"), 0.5)

--------------------------------------------------------------------------------
T.group("strings")
--------------------------------------------------------------------------------

T.eq("empty", E.decode('""'), "")
T.eq("plain", E.decode('"abc"'), "abc")
T.eq("quote", E.decode('"a\\"b"'), 'a"b')
T.eq("backslash", E.decode('"a\\\\b"'), "a\\b")
T.eq("solidus", E.decode('"a\\/b"'), "a/b")
T.eq("newline", E.decode('"a\\nb"'), "a\nb")
T.eq("tab", E.decode('"a\\tb"'), "a\tb")
T.eq("backspace, formfeed, return", E.decode('"\\b\\f\\r"'), "\b\f\r")

-- The encoder writes \u00XX for control characters and nothing else, so these
-- are the escapes a round trip actually has to survive.
T.eq("u escape ascii", E.decode('"\\u0041"'), "A")
T.eq("u escape nul", E.decode('"\\u0000"'), "\000")
T.eq("control characters round trip", round('"a\\u0001b"'), '"a\\u0001b"')

-- One case either side of each UTF-8 length boundary: a wrong constant in the
-- three-way split shows up here rather than in an airfield name.
T.eq("u escape one byte, top", E.decode('"\\u007f"'), "\127")
T.eq("u escape two bytes, bottom", E.decode('"\\u0080"'), "\194\128")
T.eq("u escape two bytes, top", E.decode('"\\u07ff"'), "\223\191")
T.eq("u escape three bytes, bottom", E.decode('"\\u0800"'), "\224\160\128")
T.eq("u escape three bytes", E.decode('"\\u20ac"'), "\226\130\172")

T.eq("utf8 passes through", E.decode('"Kutaisi \195\169"'), "Kutaisi \195\169")

--------------------------------------------------------------------------------
T.group("arrays and objects")
--------------------------------------------------------------------------------

-- The one distinction Lua cannot make on its own: both are an empty table, and
-- only the array tag separates them on the way back out.
T.eq("empty array stays an array", round("[]"), "[]")
T.eq("empty object stays an object", round("{}"), "{}")

T.eq("array", round("[1,2,3]"), "[1,2,3]")
T.eq("array of null", round("[null]"), "[null]")
T.eq("nested", round('{"a":[1,{"b":2}]}'), '{"a":[1,{"b":2}]}')
T.eq("keys come back sorted", round('{"b":1,"a":2}'), '{"a":2,"b":1}')
T.eq("whitespace between tokens", round(' { "a" : [ 1 , 2 ] } '), '{"a":[1,2]}')

local nested = string.rep("[", 60) .. string.rep("]", 60)
T.eq("nesting under the cap", #round(nested), 120)

--------------------------------------------------------------------------------
T.group("round trip")
--------------------------------------------------------------------------------

-- Manifest-shaped: a null, an empty array, an empty object, a nested object of
-- numbers, and an array of objects. Encoding it twice with a decode in between
-- has to be a fixed point.
local manifest = {
  format_version = 1,
  theatre = "Caucasus",
  crop_m = E.JSON_NULL,
  grid = { cell_size = 50, origin_x = -418650, origin_z = 113700,
           height = 8901, width = 16590, tile_size = 256 },
  complete = true,
  terrain_fingerprint = { digest = "90c9cec8", head = E.JSON_NULL, size = 4096 },
  tiles = E.as_array({ { layer = "water", tx = 0, tz = 0, min = 2, max = 2 } }),
  notes = E.as_array({}),
  timing_ms = {},
}
local once = E.json(manifest)
T.eq("manifest is a fixed point", E.json(E.decode(once)), once)

-- autoupdate.cfg's shape, with the trailing newline that makes accepting
-- whitespace after the top-level value load-bearing rather than a nicety. The
-- values are synthetic; the file on any machine states its own build.
local autoupdate = '{\n "WARNING": "DO NOT EDIT this file.",\n'
  .. ' "version": "0.0.0.0",\n "timestamp": "00000000-000000",\n'
  .. ' "arch": "x86_64",\n "modules": [\n  "WORLD",\n  "CAUCASUS_terrain"\n ]\n}\n'
T.eq("autoupdate version", E.decode(autoupdate).version, "0.0.0.0")
T.eq("autoupdate timestamp", E.decode(autoupdate).timestamp, "00000000-000000")
T.eq("autoupdate modules", E.json(E.decode(autoupdate).modules),
  '["WORLD","CAUCASUS_terrain"]')

T.eq("trailing newline", round("{}\n"), "{}")
T.eq("trailing spaces and tabs", round("1  \t\r\n"), "1")

--------------------------------------------------------------------------------
T.group("refusals")
--------------------------------------------------------------------------------

T.raises("trailing content", function() return E.decode("{} {}") end, "trailing content")
T.raises("truncated object", function() return E.decode('{"a":1') end, "expected , or }")
T.raises("truncated array", function() return E.decode("[1,2") end, "expected , or ]")
T.raises("duplicate key", function() return E.decode('{"a":1,"a":2}') end, "two members named")
T.raises("missing colon", function() return E.decode('{"a" 1}') end, "expected :")
T.raises("unquoted key", function() return E.decode("{1:2}") end, "expected a key")
T.raises("trailing comma in an object", function() return E.decode('{"a":1,}') end, "expected a key")
T.raises("trailing comma in an array", function() return E.decode("[1,]") end, "unexpected")

T.raises("leading zero", function() return E.decode("007") end, "leading zero")
T.raises("fraction with no digit", function() return E.decode("1.") end, "fraction needs a digit")
T.raises("exponent with no digit", function() return E.decode("1e") end, "exponent needs a digit")
T.raises("lone minus", function() return E.decode("-") end, "number needs a digit")

-- Infinity decodes fine and then cannot be re-encoded, so it is stopped on the
-- way in: anything this returns can be written back out.
T.raises("number out of range", function() return E.decode("1e999") end, "out of range")

T.raises("bare control character", function() return E.decode('"a\nb"') end, "control character")
T.raises("unterminated string", function() return E.decode('"abc') end, "not terminated")
T.raises("short u escape", function() return E.decode('"\\u12"') end, "four hex digits")
T.raises("unknown escape", function() return E.decode('"\\x"') end, "unknown escape")
T.raises("surrogate escape", function() return E.decode('"\\ud83d"') end, "surrogate")

T.raises("empty input", function() return E.decode("") end, "input ended early")
T.raises("a bare word", function() return E.decode("nil") end, "unexpected")
T.raises("not a string", function() return E.decode(42) end, "not a string")

local too_deep = string.rep("[", 100) .. string.rep("]", 100)
T.raises("nesting over the cap", function() return E.decode(too_deep) end, "nested deeper")

-- The position is the whole point of the error: a hand-edited manifest is
-- found by line and column, not by re-reading the file.
T.raises("reports line and column", function() return E.decode('{\n  "a": ?\n}') end,
  "line 2 column 8")

T.done()
