[package]
name = "dcsterrain-core"
description = "Extract reader, packer, packed-file reader and terrain operations."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
synth = []

[dependencies]
