[package]
name = "dcsterrain-cli"
description = "The dcsterrain command line."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "dcsterrain"
path = "src/main.rs"

[dependencies]
dcsterrain-core = { path = "../dcsterrain-core" }
